### ISSUE TITLE
Error: 3 INVALID_ARGUMENT: Language pair: en-US:tr is currently unsupported. 

### ISSUE THREAD

**Issue by ihsansengun** [googleapis/nodejs-media-translation#138]
Turkish (tr-TR) as the target language does not work.

Media Translation supports these additional languages as target languages (when the source language is English). These languages are not available as source languages.

Language | BCP-47 code
Turkish | tu-TU    - unsupported
Chinese | zh-CN -  supported
Japanese | ja-JP - supported

https://cloud.google.com/translate/media/docs/languages

**Comment by sofisl** [comment]
Hi there, 

Would you mind providing a code snippet to reproduce the failure? Thanks!

**Comment by ihsansengun** [comment]
Hi @sofisl 
To reproduce the issue, set the target language to **tu-TU**  and try running the app. it will throw an error due to the wrong BCP-47 code. I changed the BCP-47 code to **tr-TR** for Turkish, and it resolved the throwing error but did not translate. I did test all the supported langs and noticed that Turkish lang is actually not (supported) working.

**Comment by munkhuushmgl** [comment]
@ihsansengun Can u share your used audio file ?

**Comment by telpirion** [comment]
Thank you for your bug report. This repository is for the Node.js client library for Media Translation. It sounds like your issue is with the service/product itself. I recommend that you log an issue on the [cloud.google.com page that you reference](https://cloud.google.com/translate/media/docs/languages) or you log an issue on the [Translation public issue tracker](https://issuetracker.google.com/issues/new?component=187144&template=0).
